version: '3'

services:
  message-client-bundle:
    image: 019621153437.dkr.ecr.us-west-2.amazonaws.com/php-fpm-nginx:latest
    container_name: ${DOCKER_RUNNING_IMAGE_NAME}
    ports:
      - ${NGINX_PORT}80
    volumes:
      - .:/opt/app-root/src
      - ./logs/symfony:/opt/app-root/src/var/log
      - ./logs/nginx:/var/log/nginx
    env_file:
      - .env

#  message-client-bundle-nginx:
#    build: ./docker/nginx
#    container_name: ${DOCKER_RUNNING_IMAGE_NAME}-nginx
#    ports:
#      - ${NGINX_PORT}80
#    links:
#      - message-client-bundle
#    volumes:
#      - .:/opt/app-root/src
#      - ./logs/nginx:/var/log/nginx

#  message-client-bundle-rabbitmq:
#    image: library/rabbitmq:latest
#    container_name: ${DOCKER_RUNNING_IMAGE_NAME}-rabbitmq
#    volumes:
#      - ./docker/rabbitmq:/etc/rabbitmq
#    ports:
#      - ${DOCKER_RABBITMQ_PORT}5672
#      - ${DOCKER_RABBITMQ_MANAGEMENT_PORT}15672
#    healthcheck:
#      test:
#        - CMD
#        - rabbitmqctl
#        - status
